{
 "title": "Power Monitor",
 "description": "Example dashboard for HON95's Prometheus NUT Exporter.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" }
  ]
 },
 "panels": [
  {
   "title": "AC Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pwrstat_is_ac_present" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pwrstat_input_rating_voltage" }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pwrstat_battery_remaining_seconds"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pwrstat_load_watts" }
   ]
  },
  {
   "title": "Load & Battery [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(pwrstat_load_percent[$smoothing_interval]) ",
     "legendFormat": "Load"
    },
    {
     "expr": "avg_over_time(pwrstat_battery_capacity_percent[$smoothing_interval]) ",
     "legendFormat": "Battery"
    }
   ]
  },
  {
   "title": "Load [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "pwrstat_load_watts", "legendFormat": "Watts" }
   ]
  },
  {
   "title": "Voltage [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(pwrstat_input_rating_voltage[$smoothing_interval]) ",
     "legendFormat": "input"
    },
    {
     "expr": "avg_over_time(pwrstat_output_voltage[$smoothing_interval]) ",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "Runtime [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(pwrstat_battery_remaining_seconds[$smoothing_interval])",
     "legendFormat": "Runtime"
    }
   ]
  }
 ]
}