on: [push, pull_request]
name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
    - name: Run coverage
      run: make test-ci
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - run: make build
    - uses: actions/upload-artifact@v4
      with:
        name: pwrstat-exporter
        path: ./pwrstat-exporter